import { useState, useEffect } from 'react';
import { useReveal } from '@/hooks/use-reveal';
import { useLanguage } from '@/hooks/use-language';
import { Waves, Activity, Magnet } from 'lucide-react';
import { KaTeXFormula } from '@/components/katex-formula';

export function TriModal() {
  const { ref, isVisible } = useReveal();
  const { language, t } = useLanguage();
  const [activeModality, setActiveModality] = useState(0);
  const [waveSeed, setWaveSeed] = useState(0);

  // Generate dynamic waves for sensor monitors
  useEffect(() => {
    const interval = setInterval(() => {
      setWaveSeed(prev => prev + 1);
    }, 150);
    return () => clearInterval(interval);
  }, []);

  const modalities = [
    {
      id: "kinetic",
      title: language === 'en' ? "Mechanical & Kinetic Vibration" : "الاهتزاز الميكانيكي والحركي",
      sensor: language === 'en' ? "MPU6050 Accelerometer/Gyro" : "مستشعر التسارع/الدوران MPU6050",
      bus: language === 'en' ? "I2C Bus (400 kHz)" : "ناقل I2C (بسرعة 400 كيلوهرتز)",
      icon: <Activity className="w-6 h-6 text-blue-400" aria-hidden="true" />,
      desc: language === 'en' 
        ? "Monitors rotor imbalance, bearing shocks, and shaft misalignment. The system analyzes kinetic acceleration peaks at the fundamental (1X) rotation frequency to compute eccentric forces."
        : "يختص بمراقبة عدم اتزان الدوار، وصدمات المحامل، وانحراف المحور. يحلل النظام قمم التسارع الحركي عند التردد الأساسي لحساب قوى الطرد المركزي.",
      equation: "F_c = m \\cdot \\omega^2 \\cdot r",
      equationDesc: language === 'en' ? "Centrifugal force vector generated by rotor unbalance." : "متجه قوة الطرد المركزي الناتج عن عدم اتزان الدوار.",
      techNotes: language === 'en' 
        ? ["Sampling rate: 1.2 kHz", "FreeRTOS priority: Pinned Core 0", "Algorithm: FFT Power Spectrum"]
        : ["معدل العينات: 1.2 كيلوهرتز", "أولوية النظام: محجوز للنواة 0", "الخوارزمية: طيف الطاقة FFT"],
      color: "text-blue-400 border-blue-500/60",
      glowColor: "rgba(59, 130, 246, 0.4)",
      point: { x: 120, y: 150 }
    },
    {
      id: "acoustic",
      title: language === 'en' ? "Microscopic Acoustic Emissions" : "الانبعاثات الصوتية المجهرية",
      sensor: language === 'en' ? "INMP441 Digital MEMS Mic" : "ميكروفون MEMS الرقمي INMP441",
      bus: language === 'en' ? "I2S Digital Audio Bus" : "ناقل الصوت الرقمي I2S",
      icon: <Waves className="w-6 h-6 text-emerald-400" aria-hidden="true" />,
      desc: language === 'en'
        ? "Detects high-frequency mechanical friction clicks and dry bearing noise. High sampling rates capture acoustic emissions in the ultrasonic spectrum long before heat manifests."
        : "يلتقط نقرات الاحتكاك الميكانيكي عالية التردد وضوضاء محامل الدوران الجافة. تتيح معدلات أخذ العينات العالية التقاط الانبعاثات في نطاق الموجات فوق الصوتية قبل حرارة جول بفترة طويلة.",
      equation: "f_{BPFO} = \\frac{n}{2} \\cdot f_r \\cdot \\left[1 - \\frac{d}{D}\\cos(\\alpha)\\right]",
      equationDesc: language === 'en' ? "Ball Pass Frequency Outer (BPFO) bearing fault indicator." : "مؤشر عطل محمل الدوران الخارجي (BPFO).",
      techNotes: language === 'en'
        ? ["Sampling rate: 16.0 kHz", "Format: 24-bit PCM stream", "Algorithm: Wavelet Anomaly Filter"]
        : ["معدل العينات: 16.0 كيلوهرتز", "التنسيق: بث PCM بعمق 24 بت", "الخوارزمية: فلتر المويجات المتقدم للأعطال"],
      color: "text-emerald-400 border-emerald-500/60",
      glowColor: "rgba(16, 185, 129, 0.4)",
      point: { x: 280, y: 150 }
    },
    {
      id: "magnetic",
      title: language === 'en' ? "Stray Electromagnetic Flux" : "التدفق الكهرومغناطيسي الشارد",
      sensor: language === 'en' ? "A3144 Hall Effect Array" : "مصفوفة مستشعر تأثير هول A3144",
      bus: language === 'en' ? "ADC1 Channel (Direct ISR)" : "منفذ ADC1 للتحويل التماثلي المباشر (ISR)",
      icon: <Magnet className="w-6 h-6 text-amber-400" aria-hidden="true" />,
      desc: language === 'en'
        ? "Monitors distortions in the magnetic flux leaking through the motor's steel frame. A stator coil short changes the airgap reluctance, warping the magnetic stray field."
        : "يراقب التشوهات في التدفق المغناطيسي المتسرب عبر الهيكل الفولاذي للمحرك. يؤدي قصر ملف الثابت إلى تغيير ممانعة الفجوة الهوائية وتشويه المجال المغناطيسي.",
      equation: "\\mathcal{R} = \\frac{l}{\\mu \\cdot A}",
      equationDesc: language === 'en' ? "Magnetic reluctance deformation equation." : "معادلة تشوه الممانعة المغناطيسية للمحرك.",
      techNotes: language === 'en'
        ? ["Sampling rate: 5.0 kHz", "Input type: High-speed analog ADC", "Algorithm: Incremental Reluctance Variance"]
        : ["معدل العينات: 5.0 كيلوهرتز", "المدخلات: محول رقمي ADC فائق السرعة", "الخوارزمية: تباين الممانعة التدريجي"],
      color: "text-amber-400 border-amber-500/60",
      glowColor: "rgba(245, 158, 11, 0.4)",
      point: { x: 200, y: 250 }
    }
  ];

  // Helper to generate coordinates for animated wave graphs
  const getWavePath = (type: string, seed: number) => {
    let points = [];
    const width = 240;
    const height = 60;
    const midY = height / 2;
    
    for (let i = 0; i <= 20; i++) {
      const x = (i / 20) * width;
      let y = midY;
      
      if (type === 'kinetic') {
        // High amplitude, clean sine
        y = midY + Math.sin((i * 0.7) + seed * 0.4) * 20;
      } else if (type === 'acoustic') {
        // High frequency noisy spikes
        y = midY + (Math.sin((i * 1.5) + seed * 0.6) * 8) + (Math.random() * 10 - 5);
      } else if (type === 'magnetic') {
        // Slow shifting field
        y = midY + Math.cos((i * 0.3) + seed * 0.2) * 15 + Math.sin((i * 1.1) + seed * 0.3) * 6;
      }
      points.push(`${x},${y}`);
    }
    return `M ${points.join(' L ')}`;
  };

  return (
    <section className="py-24 md:py-36 border-b border-border/30 relative overflow-hidden bg-black/30" dir={language === 'ar' ? 'rtl' : 'ltr'} aria-labelledby="sensors-heading">
      {/* Visual background accents */}
      <div className="absolute top-0 right-0 w-1/3 h-full bg-[radial-gradient(circle_at_100%_50%,rgba(0,255,255,0.02)_0%,transparent_100%)] pointer-events-none" />
      <div className="absolute inset-0 tech-grid pointer-events-none opacity-20" />
      
      <div className="container mx-auto px-6 relative z-10">
        
        {/* Section Header */}
        <div className="mb-20">
          <span className="text-sm font-mono text-primary tracking-widest mb-4 border-s-2 border-primary ps-4 block">
            {t('sensing_tag')}
          </span>
          <h2 id="sensors-heading" className="text-4xl md:text-5xl font-sans font-bold text-foreground">
            {t('sensing_title')}
          </h2>
          <p className="text-muted-foreground mt-4 text-lg max-w-3xl font-sans leading-relaxed">
            {t('sensing_desc')}
          </p>
        </div>

        {/* Observation Chamber Layout */}
        <div ref={ref} className={`grid grid-cols-1 lg:grid-cols-12 gap-12 items-stretch ${isVisible ? 'reveal-visible' : 'reveal-hidden'}`}>
          
          {/* Left Column: Interactive Motor Blueprint */}
          <div className="lg:col-span-5 border border-border/40 bg-card/10 rounded-2xl p-6 flex flex-col justify-between relative overflow-hidden shadow-xl min-h-[400px]" dir="ltr">
            {/* Visual Header */}
            <div className="flex justify-between items-center mb-6 font-mono text-[9px] text-muted-foreground border-b border-border/20 pb-3">
              <span>[MOTOR_BLUEPRINT_SCHEMATIC]</span>
              <span className="text-primary font-bold">MODE: REALTIME_OBSERVATION</span>
            </div>

            {/* Schematic Graphics */}
            <div className="flex-1 flex items-center justify-center relative">
              <svg viewBox="0 0 400 300" className="w-full max-w-[340px] h-auto">
                {/* Motor Shell Outline */}
                <rect x="120" y="80" width="160" height="140" rx="10" fill="none" stroke="#1e293b" strokeWidth="2" />
                
                {/* Motor cooling fins */}
                <line x1="140" y1="60" x2="140" y2="80" stroke="#1e293b" strokeWidth="2" />
                <line x1="170" y1="60" x2="170" y2="80" stroke="#1e293b" strokeWidth="2" />
                <line x1="200" y1="60" x2="200" y2="80" stroke="#1e293b" strokeWidth="2" />
                <line x1="230" y1="60" x2="230" y2="80" stroke="#1e293b" strokeWidth="2" />
                <line x1="260" y1="60" x2="260" y2="80" stroke="#1e293b" strokeWidth="2" />

                <line x1="140" y1="220" x2="140" y2="240" stroke="#1e293b" strokeWidth="2" />
                <line x1="170" y1="220" x2="170" y2="240" stroke="#1e293b" strokeWidth="2" />
                <line x1="200" y1="220" x2="200" y2="240" stroke="#1e293b" strokeWidth="2" />
                <line x1="230" y1="220" x2="230" y2="240" stroke="#1e293b" strokeWidth="2" />
                <line x1="260" y1="220" x2="260" y2="240" stroke="#1e293b" strokeWidth="2" />

                {/* Shaft rotor */}
                <line x1="60" y1="150" x2="340" y2="150" stroke="#334155" strokeWidth="6" />
                <rect x="70" y="135" width="20" height="30" rx="3" fill="#1e293b" stroke="#334155" strokeWidth="1.5" />
                
                {/* Bearings */}
                <circle cx="130" cy="150" r="10" fill="#080B10" stroke="#475569" strokeWidth="1.5" />
                <circle cx="270" cy="150" r="10" fill="#080B10" stroke="#475569" strokeWidth="1.5" />

                {/* Stator windings */}
                <rect x="150" y="95" width="100" height="40" fill="rgba(245, 158, 11, 0.05)" stroke="rgba(245, 158, 11, 0.2)" strokeWidth="1" />
                <rect x="150" y="165" width="100" height="40" fill="rgba(245, 158, 11, 0.05)" stroke="rgba(245, 158, 11, 0.2)" strokeWidth="1" />

                {/* Interactive Sensor Nodes */}
                {modalities.map((mod, idx) => (
                  <g key={idx} className="transition-all duration-300">
                    {/* Ring highlight when active */}
                    {activeModality === idx && (
                      <circle 
                        cx={mod.point.x} 
                        cy={mod.point.y} 
                        r="18" 
                        fill="none" 
                        stroke={idx === 0 ? "hsl(var(--primary))" : idx === 1 ? "hsl(var(--cyan))" : "hsl(var(--amber))"} 
                        strokeWidth="1"
                        className="animate-ping" 
                        style={{ transformOrigin: `${mod.point.x}px ${mod.point.y}px` }}
                      />
                    )}
                    
                    {/* Sensor Node Dot */}
                    <circle 
                      cx={mod.point.x} 
                      cy={mod.point.y} 
                      r="7" 
                      fill="#080B10" 
                      stroke={idx === 0 ? "hsl(var(--primary))" : idx === 1 ? "hsl(var(--cyan))" : "hsl(var(--amber))"} 
                      strokeWidth="2.5" 
                      className="cursor-pointer" 
                      onClick={() => setActiveModality(idx)} 
                    />
                    
                    {/* Small text flag */}
                    <text 
                      x={mod.point.x} 
                      y={mod.point.y - 12} 
                      textAnchor="middle" 
                      fill={activeModality === idx ? "#fff" : "#64748b"} 
                      fontFamily="JetBrains Mono" 
                      fontSize="8" 
                      fontWeight="bold"
                    >
                      CH_0{idx + 1}
                    </text>
                  </g>
                ))}
              </svg>
            </div>

            {/* Quick calibration status footer */}
            <div className="mt-4 font-mono text-[9px] text-muted-foreground flex justify-between tracking-wide border-t border-border/20 pt-3">
              <span>INTELLIGENT FUSION: COMPLETED</span>
              <span>DEV_CLASS: DUALCORE_ESP32</span>
            </div>
          </div>

          {/* Right Column: Dynamic Channel Information and Telemetry Details */}
          <div className="lg:col-span-7 flex flex-col gap-6">
            
            {/* Horizontal Tabs to Select Modality */}
            <div className="grid grid-cols-3 gap-3 glass-card p-2 rounded-xl">
              {modalities.map((mod, idx) => (
                <button
                  key={idx}
                  onClick={() => setActiveModality(idx)}
                  className={`py-3.5 text-xs font-sans rounded-lg flex flex-col md:flex-row items-center justify-center gap-2.5 transition-all cursor-pointer hover-lift ${
                    activeModality === idx
                      ? idx === 0
                        ? 'bg-blue-500/20 text-blue-400 border border-blue-500/50 shadow-[0_0_15px_rgba(59,130,246,0.3)] font-bold'
                        : idx === 1
                        ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/50 shadow-[0_0_15px_rgba(16,185,129,0.3)] font-bold'
                        : 'bg-amber-500/20 text-amber-400 border border-amber-500/50 shadow-[0_0_15px_rgba(245,158,11,0.3)] font-bold'
                      : 'text-muted-foreground hover:text-foreground hover:bg-white/5 border border-transparent'
                  }`}
                >
                  <span className="shrink-0">{mod.icon}</span>
                  <span className="font-mono font-semibold">CH_0{idx + 1}</span>
                </button>
              ))}
            </div>

            {/* Main Info Card for Selected Modality */}
            <article className={`p-6 md:p-8 flex-1 flex flex-col justify-between relative overflow-hidden rounded-xl hover-lift ${
              activeModality === 0 
                ? 'glass-card-blue' 
                : activeModality === 1 
                ? 'glass-card-emerald' 
                : 'glass-card-amber'
            }`}>
              {/* Highlight top line */}
              <div className={`absolute top-0 left-0 w-full h-[2px] ${
                activeModality === 0 
                  ? 'bg-blue-500/50' 
                  : activeModality === 1 
                  ? 'bg-emerald-500/50' 
                  : 'bg-amber-500/50'
              }`} />
              
              <div className="space-y-6">
                <div className="flex justify-between items-start flex-wrap gap-4">
                  <div>
                    <span className={`font-mono text-xs uppercase tracking-widest ${
                      activeModality === 0 
                        ? 'text-blue-400' 
                        : activeModality === 1 
                        ? 'text-emerald-400' 
                        : 'text-amber-400'
                    }`}>
                      CH_0{activeModality + 1} // SENSOR_INPUT
                    </span>
                    <h3 className="text-2xl font-bold font-sans text-foreground mt-1">
                      {modalities[activeModality].title}
                    </h3>
                  </div>
                  
                  <span className="font-mono text-[10px] text-muted-foreground border border-white/10 px-3 py-1.5 bg-black/60 rounded-lg backdrop-blur-xs" dir="ltr">
                    {modalities[activeModality].sensor}
                  </span>
                </div>

                <p className="text-muted-foreground text-base leading-relaxed font-sans">
                  {modalities[activeModality].desc}
                </p>

                {/* Technical Specifications Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4 border-t border-white/10">
                  
                  {/* Governing Equation readout */}
                  <div className="space-y-2">
                    <span className="font-mono text-[10px] text-muted-foreground block tracking-widest uppercase">
                      {language === 'en' ? 'Governing Equation' : 'المعادلة الفيزيائية الحاكمة'}
                    </span>
                    <div className="bg-black/70 border border-white/10 p-4 rounded-xl font-mono text-sm text-foreground relative shadow-inner" dir="ltr">
                      <KaTeXFormula
                        latex={modalities[activeModality].equation}
                        displayMode={true}
                        className={`font-bold ${
                          activeModality === 0 
                            ? 'text-blue-400' 
                            : activeModality === 1 
                            ? 'text-emerald-400' 
                            : 'text-amber-400'
                        }`}
                      />
                      <p className="text-[10px] text-muted-foreground mt-2 leading-relaxed font-sans" dir={language === 'ar' ? 'rtl' : 'ltr'}>
                        {modalities[activeModality].equationDesc}
                      </p>
                    </div>
                  </div>

                  {/* Operational Telemetry Details */}
                  <div className="space-y-2">
                    <span className="font-mono text-[10px] text-muted-foreground block tracking-widest uppercase">
                      {language === 'en' ? 'Firmware Parameters' : 'محددات نظام التشغيل'}
                    </span>
                    <div className="bg-black/50 border border-white/10 p-4 rounded-xl font-mono text-[11px] text-muted-foreground space-y-2 flex flex-col justify-center">
                      {modalities[activeModality].techNotes.map((note, nIdx) => (
                        <div key={nIdx} className="flex justify-between">
                          <span>• {note.split(': ')[0]}</span>
                          <span className="text-foreground font-bold" dir="ltr">{note.split(': ')[1]}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                </div>
              </div>

              {/* Animated Live Waveform Stream Monitor */}
              <div className="mt-8 pt-6 border-t border-white/10">
                <div className="flex justify-between items-center mb-3 font-mono text-[9px] text-muted-foreground">
                  <span className="flex items-center gap-1.5">
                    <span className={`w-2 h-2 rounded-full animate-pulse ${
                      activeModality === 0 
                        ? 'bg-blue-500' 
                        : activeModality === 1 
                        ? 'bg-emerald-500' 
                        : 'bg-amber-500'
                    }`} />
                    LIVE_CHANNEL_FEED
                  </span>
                  <span dir="ltr">BUS: {modalities[activeModality].bus}</span>
                </div>
                
                <div className="h-16 w-full bg-black/80 border border-white/10 rounded-xl p-2 flex items-center relative overflow-hidden shadow-inner" dir="ltr">
                  <div className="absolute inset-0 tech-grid opacity-10" />
                  
                  <svg className="w-full h-full" preserveAspectRatio="none" viewBox="0 0 240 60">
                    <path
                      d={getWavePath(modalities[activeModality].id, waveSeed)}
                      fill="none"
                      stroke={
                        activeModality === 0 
                          ? "#60a5fa" 
                          : activeModality === 1 
                            ? "#34d399" 
                            : "#fbbf24"
                      }
                      strokeWidth="2.5"
                      className="transition-all duration-300"
                    />
                  </svg>
                </div>
              </div>

            </article>
          </div>

        </div>
      </div>
    </section>
  );
}