import { useReveal } from '@/hooks/use-reveal';
import { Waves, Activity, Magnet } from 'lucide-react';

export function TriModal() {
  const { ref, isVisible } = useReveal();

  const modalities = [
    {
      title: "Kinetic & Mechanical",
      sensor: "MPU6050",
      icon: <Activity className="w-10 h-10 text-primary" aria-hidden="true" />,
      desc: "Detects rotor imbalance and shaft misalignment using fundamental frequency (1X) spectral analysis and centrifugal force metrics.",
      math: "Fc = m * w² * r // Centrifugal force generated by rotor unbalance."
    },
    {
      title: "Acoustic & Microscopic",
      sensor: "INMP441",
      icon: <Waves className="w-10 h-10 text-primary" aria-hidden="true" />,
      desc: "Captures high-frequency acoustic emissions and friction clicks of bearing degradation and dry lubrication via a digital I2S bus.",
      math: "f_BPFO = (n/2) * f_r * [1 - (d/D)cos(alpha)] // Bearing degradation frequency."
    },
    {
      title: "Stray Electromagnetic Flux",
      sensor: "A3144 Hall",
      icon: <Magnet className="w-10 h-10 text-primary" aria-hidden="true" />,
      desc: "Identifies stator winding shorts that distort the stray magnetic flux leaking from the casing, completely non-invasively.",
      math: "R = g / (mu * A) // Magnetic reluctance distortion."
    }
  ];

  return (
    <section className="py-32 md:py-48 border-b border-border/30 relative overflow-hidden bg-background" dir="ltr" aria-labelledby="sensors-heading">
      <div className="absolute top-0 right-0 w-1/3 h-full bg-[radial-gradient(circle_at_100%_50%,rgba(0,255,65,0.03)_0%,transparent_100%)] pointer-events-none" />
      
      <div className="container mx-auto px-6 relative z-10">
        <div className="mb-24">
          <span className="text-sm font-mono text-primary tracking-widest mb-4 border-s-2 border-primary ps-4 block">
            SYSTEM_ARCHITECTURE // SENSOR_FUSION
          </span>
          <h2 id="sensors-heading" className="text-4xl md:text-5xl font-sans font-bold text-foreground">Tri-Modal Active Sensing</h2>
        </div>
        
        <div ref={ref} className={`grid grid-cols-1 lg:grid-cols-3 gap-8 ${isVisible ? 'reveal-visible' : 'reveal-hidden'}`}>
          {modalities.map((mod, i) => (
            <article 
              key={i}
              className="group relative border border-border bg-card/30 backdrop-blur-sm p-8 hover:bg-black transition-all duration-500 hover:border-primary/60 overflow-hidden rounded-xl"
            >
              <div className="absolute top-0 right-0 w-full h-px bg-linear-to-l from-transparent via-primary/0 to-transparent group-hover:via-primary group-hover:shadow-[0_0_15px_hsl(var(--primary))] transition-all duration-700" />
              
              <div className="flex justify-between items-start mb-12">
                <div className="p-3 bg-primary/5 border border-primary/20 rounded-sm group-hover:bg-primary/20 transition-colors">
                  {mod.icon}
                </div>
                <span className="font-mono text-xs text-muted-foreground border border-border px-3 py-1.5 bg-black" dir="ltr">
                  {mod.sensor}
                </span>
              </div>
              
              <h3 className="text-2xl font-bold mb-4 font-sans text-foreground">{mod.title}</h3>
              <p className="text-muted-foreground mb-12 text-base leading-relaxed min-h-20">
                {mod.desc}
              </p>
              
              <div className="pt-6 border-t border-border/50 group-hover:border-primary/30 transition-colors">
                <span className="font-mono text-[10px] text-primary/70 block mb-3 tracking-widest">GOVERNING EQUATION</span>
                <code className="font-mono text-sm md:text-base text-foreground bg-black px-4 py-3 border border-border block group-hover:border-primary/50 group-hover:text-primary transition-colors shadow-inner" dir="ltr">
                  {mod.math}
                </code>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}