import { MotorType } from '@/types/motor';

/**
 * 3D ASSET PATH CONVENTION:
 * Put motor 3D renders into `/public/motors/{slug}/{failure-mode-slug}.png`.
 * Reference them in `image3d` as `/motors/{slug}/{failure-mode-slug}.png`.
 */

export const motorsData: MotorType[] = [
  {
    category: 'DC',
    family: 'Brushed',
    slug: 'series-wound-dc-motor',
    name: 'Series-Wound DC Motor',
    overview: 'High-starting torque motor where the field winding is connected in series with the armature winding (same current flows through both). Renowned for quadratic starting torque (T ∝ I²) and catastrophic overspeed runaway hazard under no-load conditions.',
    keyEquations: [
      {
        label: 'Quadratic Developed Torque',
        latex: 'T \\propto I^{2}',
        description: 'Because stator flux is proportional to armature current (\\Phi \\propto I), torque scales quadratically with load current before magnetic saturation.'
      },
      {
        label: 'Speed-Flux Inversion (Runaway Hazard)',
        latex: 'N \\propto \\frac{1}{\\Phi}',
        description: 'Rotational speed N is inversely proportional to field flux \\Phi. As load drops to zero, flux collapses toward residual levels and speed spikes exponentially.'
      },
      {
        label: 'Field Flux Proportionality',
        latex: '\\Phi \\propto I',
        description: 'Field flux in a series motor is directly generated by the armature current flowing through the series stator coils.'
      },
      {
        label: 'Centrifugal Force on Rotor Windings',
        latex: 'F_c = m \\omega^2 r',
        description: 'Mechanical stress on rotor coils scales quadratically with angular velocity \\omega. High speeds violently eject winding conductors.'
      },
      {
        label: 'Joule Heating Dissipation',
        latex: 'P = I^{2} R',
        description: 'Resistive heat generated across commutator contact resistance and windings spikes rapidly under high currents.'
      },
      {
        label: 'Ohm\'s Law Winding Short Current Spike',
        latex: 'I = \\frac{V}{R} \\quad (R\\downarrow \\;\\Rightarrow\\; I\\uparrow)',
        description: 'Inter-turn short circuits reduce effective winding resistance R, triggering a destructive armature current spike.'
      },
      {
        label: 'Instantaneous Angular Acceleration',
        latex: '\\alpha = \\frac{d\\omega}{dt}',
        description: 'Monitored by optical tachometers to detect sudden load decoupling or mechanical rotor lock.'
      },
      {
        label: 'RMS Structural Vibration Level',
        latex: 'a_{\\mathrm{RMS}} = \\sqrt{\\frac{1}{N}\\sum_{i=1}^{N}a_i^2}',
        description: 'Evaluates structural vibration energy from MPU6050 accelerometer readings to detect mechanical looseness or bearing degradation.'
      }
    ],
    failureModes: [
      {
        title: 'Overspeed Due to Load Loss (Runaway Hazard)',
        description: 'If the mechanical load suddenly decouples, armature current drops, causing field flux \\Phi to collapse toward zero. Rotational speed N accelerates exponentially according to N ∝ 1/\\Phi, producing extreme centrifugal forces F_c = m\\omega²r that shred armature windings and shatter rotor supports.',
        relatedEquations: ['Speed-Flux Inversion (Runaway Hazard)', 'Centrifugal Force on Rotor Windings'],
        image3d: '/motors/series-wound-dc-motor/no-load-runaway.png'
      },
      {
        title: 'Carbon Brush and Commutator Wear',
        description: 'Full series current passes through the carbon brushes. Over time, high current density generates intense electrical arcing, etching copper commutator segments, increasing contact resistance R, and triggering thermal insulation breakdown via Joule heating P = I²R.',
        relatedEquations: ['Joule Heating Dissipation'],
        image3d: '/motors/series-wound-dc-motor/commutator-erosion.png'
      },
      {
        title: 'Short Circuits in Series Windings',
        description: 'Heavy industrial vibrations or sustained overheating degrade winding varnish insulation. Short-circuiting stator turns drops overall resistance R, causing an instantaneous current spike I = V/R that burns out remaining motor components.',
        relatedEquations: ['Ohm\'s Law Winding Short Current Spike'],
        image3d: '/motors/series-wound-dc-motor/insulation-breakdown.png'
      }
    ],
    sensorPlan: [
      {
        sensor: 'Optical Tachometer (Infrared Pulse Encoder)',
        purpose: 'Detect Overspeed & Sudden Load Decoupling',
        howItWorks: 'Measures shaft rotational speed (RPM) via light pulses from a reflective disc. Computes angular acceleration \\alpha = d\\omega/dt; if \\alpha exceeds critical threshold, executes an immediate electromechanical trip.',
        relatedEquation: 'Instantaneous Angular Acceleration'
      },
      {
        sensor: 'INMP441 MEMS Microphone + UV/IR Flame Sensor',
        purpose: 'Cross-Validated Brush Arcing Detection',
        howItWorks: 'INMP441 mic captures acoustic arcing noise up to 22kHz (FFT high-band spectral energy rise), while UV/IR photodiode counts light flashes. Tripping occurs only when both channels confirm arcing simultaneously.',
        relatedEquation: 'Joule Heating Dissipation'
      },
      {
        sensor: 'A3144 Hall Effect Sensor + Current Shunt + Isolation Amp',
        purpose: 'Detect Winding Short Circuits & Flux Asymmetry',
        howItWorks: 'A3144 Hall sensor monitors stray flux asymmetry non-contact, while isolated current shunt captures dI/dt spikes caused by resistance drops during inter-turn shorts.',
        relatedEquation: 'Ohm\'s Law Winding Short Current Spike'
      },
      {
        sensor: 'MPU6050 Tri-Axis Accelerometer',
        purpose: 'Structural Vibration & Bearing Health Tracking',
        howItWorks: 'Continuously samples 3-axis acceleration and computes RMS vibration level a_RMS to isolate rotor unbalance, mechanical looseness, and bearing raceway degradation.',
        relatedEquation: 'RMS Structural Vibration Level'
      },
      {
        sensor: 'MLX90614 Non-Contact Infrared Temperature Sensor',
        purpose: 'Brush Housing Thermal Trend Logging',
        howItWorks: 'Positioned near the brush/commutator housing to track surface temperature rise rate dT/dt, identifying slow heat accumulation from hard starting cycles before insulation burns.',
        relatedEquation: 'Joule Heating Dissipation'
      }
    ],
    summary: [
      'Quadratic torque dependency (T ∝ I²) provides unmatched starting torque for heavy industrial equipment.',
      'CRITICAL RISK: Must NEVER operate un-loaded; sudden decoupling causes catastrophic overspeed runaway (N ∝ 1/\\Phi).',
      'Tri-modal sensor fusion (optical + acoustic + magnetic) guarantees sub-5ms trip protection against arcing and winding faults.'
    ]
  },
  {
    category: 'DC',
    family: 'Brushed',
    slug: 'shunt-wound-dc-motor',
    name: 'Shunt-Wound DC Motor',
    overview: 'Parallel field winding motor where high field resistance (R_sh) draws a small, constant current. Delivers self-regulating constant speed across variable mechanical loads, making it ideal for pumps, conveyors, and machine tools.',
    keyEquations: [
      {
        label: 'Field Loss Speed Runaway Inversion',
        latex: 'N \\propto \\frac{1}{\\Phi}',
        description: 'Rotational speed is inversely proportional to magnetic flux. If the shunt field breaks (\\Phi \\to 0), the motor accelerates into explosive overspeed.'
      },
      {
        label: 'Armature Current Inrush Equation',
        latex: 'I_a = \\frac{V - E_b}{R_a}',
        description: 'Armature current depends on terminal voltage V, back-EMF E_b, and low armature resistance R_a.'
      },
      {
        label: 'Linear Starting Torque Relationship',
        latex: 'T \\propto I_a',
        description: 'Because shunt field flux \\Phi remains constant, starting torque scales linearly with armature current (unlike series motors).'
      },
      {
        label: 'Stall Winding Power Dissipation',
        latex: 'P = I_a^2 R_a \\quad (E_b = 0)',
        description: 'During a rotor lock (stall), back-EMF collapses to zero, forcing extreme current I_a = V/R_a and rapid resistive thermal burnout.'
      },
      {
        label: 'Shunt Field Current Equation',
        latex: 'I_f = \\frac{V}{R_{sh}}',
        description: 'Field current is independent of armature load and depends strictly on supply voltage V and shunt field resistance R_sh.'
      },
      {
        label: 'Thermal Rise Rate Integral',
        latex: '\\frac{dT}{dt}',
        description: 'Evaluated continuously to monitor cumulative thermal degradation according to Montsinger\'s 10°C insulation rule.'
      }
    ],
    failureModes: [
      {
        title: 'Shunt Field Open Circuit & Explosive Runaway Transition',
        description: 'Thermal stress or vibration breaks the thin high-resistance shunt field wire. Field flux drops toward zero (\\Phi \\to 0), driving the motor into catastrophic speed runaway (N ∝ 1/\\Phi) while the armature draws massive inrush current I_a = (V-E_b)/R_a until centrifugal forces shatter the rotor.',
        relatedEquations: ['Field Loss Speed Runaway Inversion', 'Armature Current Inrush Equation'],
        image3d: '/motors/shunt-wound-dc-motor/field-open-runaway.png'
      },
      {
        title: 'Heavy-Load Starting Stall',
        description: 'Shunt starting torque scales only linearly (T ∝ I_a). Starting under excessive mechanical load locks the rotor, reducing back-EMF to E_b = 0. Armature current spikes to I_a = V/R_a, generating extreme heat P = I_a²R_a that destroys rotor insulation within seconds.',
        relatedEquations: ['Linear Starting Torque Relationship', 'Stall Winding Power Dissipation'],
        image3d: '/motors/shunt-wound-dc-motor/heavy-load-stall.png'
      },
      {
        title: 'Supply Voltage Fluctuation & Field-Armature Imbalance',
        description: 'Supply sags reduce field current I_f = V/R_sh, causing unstable speed oscillations. Concurrently, lowered back-EMF forces the armature to draw higher current I_a = (V-E_b)/R_a, triggering severe commutator arcing and localized brush charring.',
        relatedEquations: ['Shunt Field Current Equation', 'Armature Current Inrush Equation'],
        image3d: '/motors/shunt-wound-dc-motor/voltage-sag-imbalance.png'
      },
      {
        title: 'Armature Reaction & Load-Dependent Commutator Sparking',
        description: 'High armature current creates its own cross-magnetic field, shifting the magnetic neutral axis (MNA). Commutator segments break contact while still carrying active EMF, producing arcing that scales directly with load.',
        relatedEquations: ['Linear Starting Torque Relationship'],
        image3d: '/motors/shunt-wound-dc-motor/neutral-plane-shift.png'
      },
      {
        title: 'Cumulative Thermal Aging from Sustained Overload',
        description: 'Prolonged overload increases resistive losses P = I_a²R_a. According to Montsinger\'s rule, every 10°C temperature increase above rated limits reduces winding insulation lifetime by approximately 50%.',
        relatedEquations: ['Thermal Rise Rate Integral'],
        image3d: '/motors/shunt-wound-dc-motor/cumulative-thermal-aging.png'
      }
    ],
    sensorPlan: [
      {
        sensor: 'Dedicated Field Current Sensor (ACS712/ACS758)',
        purpose: 'Detect Open Field Circuit (Earliest Runaway Warning)',
        howItWorks: 'Monitors field winding current I_f independently from armature current. An abrupt drop in I_f while supply voltage is present triggers an instant safety shutdown before speed runaway occurs.',
        relatedEquation: 'Shunt Field Current Equation'
      },
      {
        sensor: 'Optical Tachometer',
        purpose: 'Secondary Speed Verification & Acceleration Check',
        howItWorks: 'Monitors shaft RPM and computes acceleration \\alpha = d\\omega/dt. Cross-checks field current alarms to prevent false triggers from supply noise.',
        relatedEquation: 'Field Loss Speed Runaway Inversion'
      },
      {
        sensor: 'Armature Inrush Current Sensor (ACS712/ACS758)',
        purpose: 'Per-Start Thermal Stress & Overload Monitoring',
        howItWorks: 'Logs armature starting current profiles and computes thermal stress integral \\int I_a² dt to track cumulative winding fatigue.',
        relatedEquation: 'Armature Current Inrush Equation'
      },
      {
        sensor: 'INMP441 MEMS Mic + UV/IR Photodiode (Sensor Fusion)',
        purpose: 'Load-Triggered Neutral Shift Arcing Verification',
        howItWorks: 'Fuses high-band acoustic FFT energy, optical spark counts, and armature load current to isolate neutral-plane shift arcing from background ambient noise.',
        relatedEquation: 'Linear Starting Torque Relationship'
      },
      {
        sensor: 'MPU6050 Accelerometer',
        purpose: 'Vibration & Mechanical Looseness Diagnostics',
        howItWorks: 'Measures tri-axial RMS acceleration a_RMS to identify bearing race wear, shaft misalignment, and mechanical unbalance.',
        relatedEquation: 'RMS Structural Vibration Level'
      },
      {
        sensor: 'MLX90614 Non-Contact IR Sensor',
        purpose: 'Long-Term Winding Thermal Degradation Logging',
        howItWorks: 'Tracks armature housing surface temperature and rise rate dT/dt to enforce Montsinger\'s thermal life envelope.',
        relatedEquation: 'Thermal Rise Rate Integral'
      }
    ],
    summary: [
      'Self-regulating constant speed characteristics suited for continuous manufacturing applications.',
      'CRITICAL HAZARD: Open field circuit (I_f → 0) leads to destructive speed runaway; dedicated field sensing is mandatory.',
      'Sensor fusion monitors field current, armature starting profiles, acoustic arcing, and Montsinger thermal aging trends.'
    ]
  },
  {
    category: 'DC',
    family: 'Brushed',
    slug: 'compound-wound-dc-motor',
    name: 'Compound-Wound DC Motor',
    overview: 'Hybrid motor featuring both series and shunt field windings on the same magnetic poles. Combines the high starting torque of series motors with the safe no-load speed limiting of shunt motors.',
    keyEquations: [
      {
        label: 'Dual Branch Current Ratio',
        latex: '\\text{Ratio} = \\frac{I_{sh}}{I_a}',
        description: 'Continuously evaluated to distinguish partial field loss (I_sh \\to 0) from normal load variations or field coupling degradation.'
      },
      {
        label: 'Adaptive Load-Dependent Speed Deviation',
        latex: '\\Delta N = N_{\\text{actual}} - N_{\\text{expected}}(I_a)',
        description: 'Evaluates shaft speed against the motor\'s compounding droop curve N_expected(I_a) to detect field anomalies without false alarms.'
      },
      {
        label: 'Direct Pole-Face Air-Gap Flux Density',
        latex: 'B_{\\text{actual}} \\propto (\\Phi_{sh} \\pm \\Phi_{se})',
        description: 'Measured directly at the stator pole face by Hall-effect sensors to isolate internal coil short circuits.'
      },
      {
        label: 'Acoustic-Optical Compound Arcing Rule',
        latex: '\\text{Arcing Fault} = (\\text{FFT}_{\\text{high-freq}} > \\text{Threshold}_{\\text{compound}}) \\;\\land\\; (\\text{Spark Count} > N_{\\text{limit}})',
        description: 'Cross-validates acoustic sub-band energy and optical spark pulse counts calibrated specifically for combined MMF neutral shift.'
      },
      {
        label: 'Dual Winding Resistive Heating Loss',
        latex: 'P = I_a^2 (R_{se} + R_a) + I_{sh}^2 R_{sh}',
        description: 'Accounts for thermal dissipation across both the series winding path and high-resistance shunt field.'
      },
      {
        label: 'Fast Reactive Thermal Energy Integral',
        latex: 'E_{\\text{thermal}} \\propto \\int I_a^2 \\, dt',
        description: 'High-speed hardware integration loop monitoring armature current for instant stall protection.'
      }
    ],
    failureModes: [
      {
        title: 'Partial Field Loss Hazard (Shunt Winding Open Circuit)',
        description: 'If the shunt winding breaks, the motor relies solely on the series winding. Under light load (low I_a), series flux is minimal, causing partial speed runaway (N_actual >> N_expected). Under heavy load, series flux prevents runaway but speed droop shifts radically.',
        relatedEquations: ['Dual Branch Current Ratio', 'Adaptive Load-Dependent Speed Deviation'],
        image3d: '/motors/compound-wound-dc-motor/partial-field-loss.png'
      },
      {
        title: 'Combined MMF Neutral-Plane Shift',
        description: 'Both series and shunt field MMFs distort the main air-gap flux under load. Neutral-plane shift and brush arcing initiate at lower load thresholds than in equivalent shunt motors, demanding lower diagnostic thresholds.',
        relatedEquations: ['Direct Pole-Face Air-Gap Flux Density', 'Acoustic-Optical Compound Arcing Rule'],
        image3d: '/motors/compound-wound-dc-motor/combined-mmf-shift.png'
      },
      {
        title: 'Dual-Winding Cumulative Thermal Aging',
        description: 'Heat is generated across two distinct paths: steady dissipation in the shunt field and load-dependent I_a²R_se heating in the series field. Sustained overloads accelerate insulation aging faster than in pure shunt designs.',
        relatedEquations: ['Dual Winding Resistive Heating Loss'],
        image3d: '/motors/compound-wound-dc-motor/dual-winding-thermal-aging.png'
      }
    ],
    sensorPlan: [
      {
        sensor: 'Dual Independent Current Sensors (2x ACS712/ACS758)',
        purpose: 'Shunt vs Armature Current Ratio Monitoring',
        howItWorks: 'Measures I_sh and I_a independently. Computes ratio I_sh/I_a to isolate partial field loss from magnetic coupling degradation.',
        relatedEquation: 'Dual Branch Current Ratio'
      },
      {
        sensor: 'Adaptive Optical Tachometer',
        purpose: 'Compounding Droop Speed Deviation Analysis',
        howItWorks: 'Compares real-time RPM against expected speed curve N_expected(I_a); positive deviations (\\Delta N > 0) flag runaway hazards.',
        relatedEquation: 'Adaptive Load-Dependent Speed Deviation'
      },
      {
        sensor: 'A3144 Hall Effect Sensor (Stator Pole Face)',
        purpose: 'Direct Air-Gap Flux Measurement',
        howItWorks: 'Mounted directly on the stator pole face to measure actual magnetic flux B_actual non-contact, catching turn-to-turn winding shorts.',
        relatedEquation: 'Direct Pole-Face Air-Gap Flux Density'
      },
      {
        sensor: 'Calibrated Acoustic-Optical Sensor Fusion',
        purpose: 'Early Commutation Spark Detection',
        howItWorks: 'Combines INMP441 MEMS microphone acoustic FFT analysis with UV/IR photodiode spark counting calibrated for compound MMF shifts.',
        relatedEquation: 'Acoustic-Optical Compound Arcing Rule'
      },
      {
        sensor: 'Dual Infrared Thermal Proxies (2x MLX90614)',
        purpose: 'Independent Shunt & Series Winding Hotspot Tracking',
        howItWorks: 'Sensor A targets the shunt pole housing while Sensor B targets series winding and commutator assembly to log surface rise rates dT/dt.',
        relatedEquation: 'Dual Winding Resistive Heating Loss'
      },
      {
        sensor: 'Fast Reactive I²t Protection Logic',
        purpose: 'Millisecond Hardware Lock Cutoff',
        howItWorks: 'Monitors armature current on a fast ISR loop, integrating thermal energy E_thermal to execute instant trip during mechanical stall.',
        relatedEquation: 'Fast Reactive Thermal Energy Integral'
      }
    ],
    summary: [
      'Blends series motor starting torque with shunt motor no-load speed limiting.',
      'Requires dual current sensing (I_sh vs I_a) to detect partial field loss before overspeed occurs.',
      'Multi-sensor fusion combines direct air-gap flux sensing, dual IR thermal proxies, and fast I²t hardware trip logic.'
    ]
  },
  {
    category: 'DC',
    family: 'Brushed',
    slug: 'permanent-magnet-dc-motor',
    name: 'Permanent-Magnet DC Motor (PMDC)',
    overview: 'Brushed motor using permanent magnets for field excitation instead of field windings. Features simple, compact single-current-path design, but fragile magnetic flux (\\Phi) is vulnerable to thermal and electrical demagnetization.',
    keyEquations: [
      {
        label: 'Electromagnetic Developed Torque',
        latex: 'T = K_t \\Phi I_a',
        description: 'Torque depends directly on permanent magnet flux \\Phi and armature current I_a.'
      },
      {
        label: 'Back-EMF Voltage Equation',
        latex: 'E_b = K_e \\Phi \\omega',
        description: 'Back-EMF voltage is proportional to rotational speed \\omega and magnet flux \\Phi.'
      },
      {
        label: 'Demagnetizing Field Strength MMF',
        latex: 'H_d = \\beta(T_m) \\cdot I_a',
        description: 'Armature reaction MMF directly opposes permanent magnet field; demagnetization factor \\beta(T_m) spikes with magnet temperature T_m.'
      },
      {
        label: 'Thermal Flux Decay Function',
        latex: '\\Phi(T) = \\Phi_0 \\left[1 - \\alpha_T (T_m - T_0)\\right]',
        description: 'Models reversible and irreversible magnet flux reduction as magnet surface temperature T_m increases.'
      },
      {
        label: 'Neutral Axis Displacement Angle',
        latex: '\\theta_{\\text{shift}} = \\tan^{-1}\\left(\\frac{\\text{MMF}_a}{\\text{MMF}_m}\\right) \\propto \\frac{I_a}{\\Phi}',
        description: 'Armature reaction shifts the geometric neutral plane; flux decay (\\Phi \\downarrow) drastically amplifies neutral-plane distortion.'
      },
      {
        label: 'Flux-Compensated Rotational Speed',
        latex: 'N_{\\text{expected}} = \\frac{V - I_a R_a}{K_e \\cdot \\Phi_{\\text{actual}}}',
        description: 'Dynamically updates expected RPM using live air-gap flux readings to prevent false speed anomalies.'
      },
      {
        label: 'Accumulating Thermal Energy Integral',
        latex: 'E_{\\text{thermal}} = \\int_0^t I_a^2(\\tau) \\, d\\tau',
        description: 'High-speed integration channel tracking rotor heat accumulation for instant stall disconnection.'
      }
    ],
    failureModes: [
      {
        title: 'Irreversible Magnetic Demagnetization / Flux Fade',
        description: 'High armature current generates strong opposing MMF H_d. Combined with elevated magnet temperature T_m, permanent magnets lose flux density (\\Phi \\downarrow). To maintain torque T, the motor draws higher current I_a = T / (K_t\\Phi), generating more heat P = I_a²R_a in a self-reinforcing demagnetization feedback loop.',
        relatedEquations: ['Electromagnetic Developed Torque', 'Demagnetizing Field Strength MMF', 'Thermal Flux Decay Function'],
        image3d: '/motors/permanent-magnet-dc-motor/magnetic-demagnetization.png'
      },
      {
        title: 'Carbon Brush and Commutator Wear',
        description: 'Mechanical carbon brush friction creates copper etching, conductive dust accumulation, and electrical arcing (P_spark ∝ I_a² R_contact), matching wear mechanisms in wound-field brushed motors.',
        relatedEquations: ['Electromagnetic Developed Torque'],
        image3d: '/motors/permanent-magnet-dc-motor/brush-commutator-wear.png'
      },
      {
        title: 'Uncompensated Neutral-Plane Shift',
        description: 'Lacking field windings to stabilize flux, high armature currents shift the geometric neutral axis by angle \\theta_shift ∝ I_a/\\Phi. As magnets degrade (\\Phi \\downarrow), neutral shift widens rapidly, causing severe commutation arcing.',
        relatedEquations: ['Neutral Axis Displacement Angle'],
        image3d: '/motors/permanent-magnet-dc-motor/neutral-axis-shift.png'
      },
      {
        title: 'Magnet-Critical Thermal Aging',
        description: 'Unlike wound motors constrained by insulation rating, PMDC thermal limits are governed by the magnet\'s maximum operating temperature T_max or Curie point T_c. Exceeding T_max causes permanent, unrecoverable loss of remanence.',
        relatedEquations: ['Thermal Flux Decay Function'],
        image3d: '/motors/permanent-magnet-dc-motor/magnet-thermal-aging.png'
      }
    ],
    sensorPlan: [
      {
        sensor: 'Armature Current Sensor (ACS712/ACS758)',
        purpose: 'Demagnetization MMF Modeling & Heating Tracking',
        howItWorks: 'Tracks I_a to continuously compute resistive heat P = I_a²R_a and estimate opposing demagnetization field H_d = \\beta(T_m) I_a.',
        relatedEquation: 'Demagnetizing Field Strength MMF'
      },
      {
        sensor: 'Direct Pole-Face Flux Sensor (A3144 Hall Effect)',
        purpose: 'Air-Gap Magnetic Flux Fade Diagnostic',
        howItWorks: 'Mounted on the stator pole face to measure air-gap flux density B_actual over rolling multi-week windows, capturing gradual flux fade before failure.',
        relatedEquation: 'Thermal Flux Decay Function'
      },
      {
        sensor: 'Dedicated Magnet Housing IR Sensor (MLX90614)',
        purpose: 'Magnet Case Temperature & Limit Protection',
        howItWorks: 'Aimed directly at the permanent magnet casing to monitor surface temperature T_m and rise rate dT_m/dt against T_demag safety limits.',
        relatedEquation: 'Thermal Flux Decay Function'
      },
      {
        sensor: 'Dynamic Flux-Compensated Optical Tachometer',
        purpose: 'Flux-Adjusted Shaft RPM Monitoring',
        howItWorks: 'Evaluates measured speed against N_expected auto-adjusted by live Hall sensor flux readings to differentiate mechanical jams from demagnetization.',
        relatedEquation: 'Flux-Compensated Rotational Speed'
      },
      {
        sensor: 'Acoustic-Optical Sensor Fusion (INMP441 + UV/IR)',
        purpose: 'Brush Arcing & Neutral Shift Detection',
        howItWorks: 'Combines acoustic FFT high-band energy with optical spark counts; automatically recalibrates thresholds when Hall flux drops.',
        relatedEquation: 'Neutral Axis Displacement Angle'
      },
      {
        sensor: 'Fast Reactive I²t Protection Circuit',
        purpose: 'Millisecond Stall Disconnection',
        howItWorks: 'Monitors armature line for stall conditions (E_b = 0, I_stall = V/R_a) and disconnects power within milliseconds if E_thermal exceeds safe limits.',
        relatedEquation: 'Accumulating Thermal Energy Integral'
      }
    ],
    summary: [
      'Compact, high-efficiency brushed topology featuring single current path control.',
      'Primary fault mode is magnet demagnetization (\\Phi \\downarrow), creating a dangerous thermal-current feedback loop.',
      'Diagnostics depend on direct air-gap magnetic flux sensing (Hall effect) fused with magnet casing IR thermography.'
    ]
  },
  {
    category: 'DC',
    family: 'Brushless',
    slug: 'brushless-dc-motor',
    name: 'Brushless DC Motor (BLDC)',
    overview: 'Brushless motor topology using permanent magnets on the rotor and 3-phase stator windings electronically commutated via an inverter. Eliminates mechanical brush wear, shifting reliability factors to electronic timing, phase symmetry, and PWM eddy losses.',
    keyEquations: [
      {
        label: 'Commutation Angle Torque Degradation',
        latex: 'T = K_t \\Phi I \\cos(\\theta_{\\text{error}})',
        description: 'Torque output is degraded by the cosine of the electrical commutation timing error angle \\theta_error.'
      },
      {
        label: 'Commutation Error Current Compensation',
        latex: 'I_{\\text{required}} = \\frac{T_{\\text{load}}}{K_t \\Phi \\cos(\\theta_{\\text{error}})}',
        description: 'Shows why timing drift forces the inverter to inject higher phase current to sustain the same mechanical load.'
      },
      {
        label: 'Three-Phase Current Residual Symmetry',
        latex: 'I_{\\text{neutral\\_residual}} = I_A(t) + I_B(t) + I_C(t) = 0',
        description: 'Under balanced operation, phase currents sum to zero. Phase shorts or open circuits cause a non-zero residual sum.'
      },
      {
        label: 'Switching Inverter Eddy Current Loss',
        latex: 'P_{\\text{eddy}} \\propto f_{\\text{PWM}}^2 B_{\\text{ripple}}^2',
        description: 'High-frequency PWM inverter switching induces eddy current heating directly inside rotor permanent magnets.'
      },
      {
        label: 'Phase Demagnetization MMF Force',
        latex: 'H_d = \\beta(T_m) \\cdot I_{\\text{phase}}',
        description: 'Phase current MMF combined with PWM eddy heating drives localized magnet demagnetization.'
      }
    ],
    failureModes: [
      {
        title: 'Commutation Timing Fault (Hall Sensor Misalignment / Drift)',
        description: 'Physical drift or electronic degradation in Hall position sensors causes phase switching at an incorrect electrical angle \\theta_error. Current flows partially against rotor rotation, dropping torque T = K_t\\Phi I cos(\\theta_error) and forcing higher current draw that induces severe torque ripple and vibration.',
        relatedEquations: ['Commutation Angle Torque Degradation', 'Commutation Error Current Compensation'],
        image3d: '/motors/brushless-dc-motor/commutation-timing-fault.png'
      },
      {
        title: 'Phase Winding Short or Open Circuit',
        description: 'Inter-turn insulation breakdown or open circuit in one stator phase disrupts electrical symmetry, causing phase amplitude divergence and non-zero residual current I_A + I_B + I_C ≠ 0 that generates intense high-frequency torque ripple.',
        relatedEquations: ['Three-Phase Current Residual Symmetry'],
        image3d: '/motors/brushless-dc-motor/phase-winding-short.png'
      },
      {
        title: 'Magnet Demagnetization Under Switching-Induced Heating',
        description: 'High PWM switching frequencies induce eddy current losses P_eddy ∝ f_PWM² B_ripple² directly in rotor magnets. Elevated magnet temperature T_m increases demagnetization susceptibility H_d = \\beta(T_m) I_phase, producing localized flux loss.',
        relatedEquations: ['Switching Inverter Eddy Current Loss', 'Phase Demagnetization MMF Force'],
        image3d: '/motors/brushless-dc-motor/pwm-eddy-demagnetization.png'
      },
      {
        title: 'Bearing Raceway Wear (Sole Mechanical Failure Mode)',
        description: 'Eliminating brushes leaves bearing raceway wear as the primary mechanical failure path. Raceway pitting and cage degradation generate distinct vibration harmonic frequencies (BPFO/BPFI).',
        relatedEquations: ['Commutation Angle Torque Degradation'],
        image3d: '/motors/brushless-dc-motor/bearing-raceway-wear.png'
      }
    ],
    sensorPlan: [
      {
        sensor: 'Three-Phase Current Sensor Array (3x ACS712/ACS758)',
        purpose: 'Phase Amplitude Divergence & Residual Symmetry Tracking',
        howItWorks: 'Monitors I_A, I_B, I_C in real time. Computes phase symmetry ratio and residual sum I_neutral_residual to detect inter-turn shorts and open phases instantly.',
        relatedEquation: 'Three-Phase Current Residual Symmetry'
      },
      {
        sensor: 'Digital Hall Encoder & Commutation Timing Analyzer',
        purpose: 'Commutation Timing Drift & Angle Error Detection',
        howItWorks: 'Measures timing interval between Hall position signals and phase current zero-crossings to extract electrical timing error angle \\theta_error.',
        relatedEquation: 'Commutation Angle Torque Degradation'
      },
      {
        sensor: 'Multi-Point Stator & Rotor IR Thermal Array (2x MLX90614)',
        purpose: 'PWM Eddy Loss & Stator Hotspot Monitoring',
        howItWorks: 'Monitors stator coil surfaces and rotor casing to detect localized thermal spikes driven by high PWM switching frequencies.',
        relatedEquation: 'Switching Inverter Eddy Current Loss'
      },
      {
        sensor: 'Tri-Axis MEMS Accelerometer (MPU6050)',
        purpose: 'Bearing Fault Pass Frequency FFT Diagnostics',
        howItWorks: 'High-frequency vibration spectral analysis isolates bearing ball pass frequencies (BPFO/BPFI) and commutation torque ripple harmonics.',
        relatedEquation: 'Commutation Angle Torque Degradation'
      },
      {
        sensor: 'Fast Inverter Microsecond Hardware Comparator Circuit',
        purpose: 'Inverter Bridge Overcurrent & Short-Circuit Protection',
        howItWorks: 'Monitors DC bus and phase lines with high-speed analog comparators to shut down inverter gate drivers within <2µs during phase short circuits.',
        relatedEquation: 'Three-Phase Current Residual Symmetry'
      }
    ],
    summary: [
      'High-efficiency, low-maintenance brushless topology relying on 3-phase inverter electronic commutation.',
      'Failure modes transition from mechanical brush friction to electronic timing drift, phase current asymmetry, and PWM eddy magnet heating.',
      '3-phase current symmetry monitoring and high-frequency vibration FFT form the core edge predictive defense.'
    ]
  },
  {
    category: 'AC',
    family: 'Induction',
    slug: 'squirrel-cage-induction-motor',
    name: 'Squirrel-Cage Induction Motor',
    overview: 'The absolute workhorse of industrial automation. Operates via 3-phase AC stator rotating magnetic field (RMF) that sweep short-circuited rotor conductive bars, inducing currents and mechanical torque without brushes or commutators.',
    keyEquations: [
      {
        label: 'Synchronous Stator Speed',
        latex: 'N_s = \\frac{120 f_s}{P}',
        description: 'Synchronous rotational speed N_s determined by line frequency f_s and pole count P.'
      },
      {
        label: 'Rotor Slip Factor',
        latex: 's = \\frac{N_s - N_r}{N_s}',
        description: 'Rotor speed N_r must lag behind synchronous speed N_s to cut magnetic flux lines and induce current.'
      },
      {
        label: 'Thermal Expansion Bar Shear Stress',
        latex: '\\Delta L = L_0 \\cdot \\alpha \\cdot \\Delta T',
        description: 'Differential thermal expansion between copper/aluminum bars and iron core causes joint shear at end-rings during DOL starts.'
      },
      {
        label: 'Broken Bar Current Sideband Frequencies',
        latex: 'f_{\\text{sideband}} = (1 \\pm 2s) f_s',
        description: 'Broken rotor bars break electrical symmetry, producing characteristic sideband frequency harmonics in stator current FFT.'
      },
      {
        label: 'Unbalanced Magnetic Pull (UMP)',
        latex: 'F_{\\text{UMP}} \\propto \\left(\\frac{1}{\\delta_{\\min}^2} - \\frac{1}{\\delta_{\\max}^2}\\right)',
        description: 'Air-gap radial eccentricity generates continuous net radial magnetic force pulling the rotor toward narrower gap side.'
      }
    ],
    failureModes: [
      {
        title: 'Broken Rotor Bar & End-Ring Joint Fracture',
        description: 'Direct-on-line (DOL) starts induce 6-8x rated current surges, causing severe thermal shear stress ΔL = L₀ α ΔT at bar-to-end-ring joints. Fractures create localized dead spots in torque and produce (1±2s)f_s current sideband frequencies.',
        relatedEquations: ['Thermal Expansion Bar Shear Stress', 'Broken Bar Current Sideband Frequencies'],
        image3d: '/motors/squirrel-cage-induction-motor/broken-rotor-bar.png'
      },
      {
        title: 'Stator Winding Insulation & Inter-Turn Fault Cascade',
        description: 'PWM VFD steep voltage wavefronts (dV/dt) degrade slot insulation varnish. Turn-to-turn short loops draw high circulating current I_short, escalating to catastrophic phase-to-ground faults.',
        relatedEquations: ['Broken Bar Current Sideband Frequencies'],
        image3d: '/motors/squirrel-cage-induction-motor/stator-insulation-fault.png'
      },
      {
        title: 'Dynamic Air-Gap Eccentricity & Bearing Fluting (EDM)',
        description: 'Bearing wear shifts rotor alignment, generating net Unbalanced Magnetic Pull (UMP). Inverter common-mode voltages spark micro-arcs through bearing grease, leaving fluting ridges on raceways.',
        relatedEquations: ['Unbalanced Magnetic Pull (UMP)'],
        image3d: '/motors/squirrel-cage-induction-motor/eccentricity-fluting.png'
      }
    ],
    sensorPlan: [
      {
        sensor: 'Optical Tachometer / Shaft Speed Sensor',
        purpose: 'Inrush Acceleration & Breakdown Slip Cutoff',
        howItWorks: 'Monitors starting slip s and acceleration rate; executes immediate cutoff if slip exceeds critical breakdown slip s_breakdown.',
        relatedEquation: 'Rotor Slip Factor'
      },
      {
        sensor: 'INMP441 MEMS Microphone + Current FFT',
        purpose: 'Fused Acoustic & Current Spectrum Analysis',
        howItWorks: 'Cross-validates 2sf_s acoustic beating from INMP441 with stator current FFT sidebands (1±2s)f_s to confirm broken rotor bars without false alarms.',
        relatedEquation: 'Broken Bar Current Sideband Frequencies'
      },
      {
        sensor: 'Three-Phase Current Sensor Array (ACS712/ACS758)',
        purpose: 'Thermal Inrush & Phase Equilibrium Profiling',
        howItWorks: 'Logs starting current integral ∫I²dt per start and tracks phase symmetry I_A + I_B + I_C = 0 for turn-to-turn shorts.',
        relatedEquation: 'Synchronous Stator Speed'
      },
      {
        sensor: 'MPU6050 3-Axis Accelerometer',
        purpose: 'UMP Radial Vibration & Bearing Fluting Tracking',
        howItWorks: 'Computes RMS vibration a_RMS and performs PSD spectral analysis to isolate 1x/2x RPM eccentricities and bearing raceway fluting.',
        relatedEquation: 'Unbalanced Magnetic Pull (UMP)'
      },
      {
        sensor: 'MLX90614 Non-Contact IR Sensor',
        purpose: 'Continuous Stator Thermal Rise Logging',
        howItWorks: 'Monitors surface thermal rise rate dT/dt to predict winding insulation thermal life envelope according to Montsinger\'s rule.',
        relatedEquation: 'Thermal Expansion Bar Shear Stress'
      }
    ],
    summary: [
      'Rugged, brush-free AC workhorse operating on electromagnetic induction.',
      'Primary failure points: rotor bar thermal expansion joint fracture, stator VFD dV/dt insulation degradation, and EDM bearing fluting.',
      'Multi-channel diagnostic defense combines current FFT sideband analysis, fused acoustic beating, and tri-axial vibration PSD.'
    ]
  },
  {
    category: 'AC',
    family: 'Induction',
    slug: 'wound-rotor-induction-motor',
    name: 'Wound-Rotor (Slip-Ring) Induction Motor',
    overview: 'Heavy-duty AC induction motor with 3-phase insulated rotor windings connected via slip rings and carbon brushes to external resistor banks, enabling maximum starting torque with reduced inrush current.',
    keyEquations: [
      {
        label: 'External Resistance Shifted Torque',
        latex: 'T \\propto \\frac{s V^2 R_r}{R_r^2 + (s X_r)^2}',
        description: 'Injecting external resistance R_ext into rotor circuit shifts maximum breakdown torque point to zero speed (s = 1.0).'
      },
      {
        label: 'Rotor Open-Circuit Standstill Voltage',
        latex: 'V_r = s \\cdot E_{\\text{rotor, standstill}}',
        description: 'Rotor open-circuit voltage spikes to maximum at standstill (s = 1.0) during Direct-On-Line starting.'
      },
      {
        label: 'Single-Phasing Maximum Torque Reduction',
        latex: 'T_{\\text{max, single-phase}} < 0.5 \\times T_{\\text{max, 3-phase}}',
        description: 'Opening a rotor phase drops maximum available torque by over 50% and causes heavy 2sf_s vibration.'
      },
      {
        label: 'Twice-Slip Frequency Vibration Harmonic',
        latex: 'f_{\\text{vibe}} = 2 \\cdot s \\cdot f_s',
        description: 'Unbalanced rotor phase current generates characteristic mechanical vibration harmonic at twice slip frequency.'
      }
    ],
    failureModes: [
      {
        title: 'Slip Ring Arcing & Rotor Phase Open-Circuit',
        description: 'Carbon brush friction and arcing open a rotor phase (I_r,A = 0). The motor drops into single-phasing operation, losing >50% torque capability and generating 2sf_s vibration.',
        relatedEquations: ['Single-Phasing Maximum Torque Reduction', 'Twice-Slip Frequency Vibration Harmonic'],
        image3d: '/motors/wound-rotor-induction-motor/slip-ring-arcing.png'
      },
      {
        title: 'External Resistor Overload & Asymmetric Resistance',
        description: 'Stuck contactors keep external starting resistors continuously energized. Severe heating causes asymmetric phase resistance R_ext,A ≠ R_ext,B, triggering current unbalance and thermal runaway.',
        relatedEquations: ['External Resistance Shifted Torque'],
        image3d: '/motors/wound-rotor-induction-motor/resistor-overload.png'
      },
      {
        title: 'Rotor Coil Inter-Turn Insulation Breakdown',
        description: 'High standstill voltage spikes V_r = s E_rotor combined with centrifugal throw F_c = mω²r degrade winding end-turn insulation, leading to internal rotor coil short circuits.',
        relatedEquations: ['Rotor Open-Circuit Standstill Voltage'],
        image3d: '/motors/wound-rotor-induction-motor/rotor-insulation-breakdown.png'
      }
    ],
    sensorPlan: [
      {
        sensor: 'Optical Tachometer',
        purpose: 'Startup Speed Acceleration & High Slip Verification',
        howItWorks: 'Tracks speed buildup against external resistor stepping sequence; flags stuck contactors if s > s_nominal.',
        relatedEquation: 'External Resistance Shifted Torque'
      },
      {
        sensor: 'Acoustic-Optical Fusion (INMP441 + UV/IR Photodiode)',
        purpose: 'Slip Ring Arcing & Brush Wear Validation',
        howItWorks: 'Cross-validates high-band acoustic emissions (INMP441) with UV/IR photodiode spark counts to eliminate false ambient noise triggers.',
        relatedEquation: 'Single-Phasing Maximum Torque Reduction'
      },
      {
        sensor: 'A3144 Hall Effect Sensor + Isolated Current Shunt',
        purpose: 'Rotor Phase Symmetry & Winding Short Detection',
        howItWorks: 'Measures phase current equilibrium I_A + I_B + I_C = 0 and detects localized flux distortions ΔB_airgap caused by coil shorts.',
        relatedEquation: 'Rotor Open-Circuit Standstill Voltage'
      },
      {
        sensor: 'MPU6050 Accelerometer',
        purpose: 'Twice-Slip Vibration Spectrum Diagnostics',
        howItWorks: 'Samples chassis vibration and performs FFT to isolate 2sf_s frequency peaks diagnostic of single-phasing rotor unbalance.',
        relatedEquation: 'Twice-Slip Frequency Vibration Harmonic'
      },
      {
        sensor: 'MLX90614 Infrared Temperature Sensor',
        purpose: 'Brush Housing & Resistor Bank Hotspot Tracking',
        howItWorks: 'Monitors brush housing and external resistor thermal rise rates dT/dt to prevent thermal runaway.',
        relatedEquation: 'External Resistance Shifted Torque'
      }
    ],
    summary: [
      'High starting torque topology for extreme inertia industrial loads.',
      'Reintroduces slip ring sliding contact arcing, brush wear, and high-voltage rotor coil failure paths.',
      'Acoustic-optical spark validation fused with 2sf_s vibration FFT provides early fault warning.'
    ]
  },
  {
    category: 'AC',
    family: 'Synchronous',
    slug: 'wound-field-synchronous-motor',
    name: 'Electrically Excited Synchronous Motor',
    overview: 'High-power AC motor featuring a DC-excited rotor field locking synchronously with the stator rotating field at exactly zero slip. Enables constant speed operation and industrial power factor correction.',
    keyEquations: [
      {
        label: 'Developed Synchronous Power',
        latex: 'P_{\\text{developed}} = \\frac{3 V_s E_f}{X_d} \\sin(\\delta)',
        description: 'Developed power depends on internal excitation voltage E_f (proportional to field current I_f) and power angle \\delta.'
      },
      {
        label: 'Zero Slip Synchronous Condition',
        latex: 's = 0 \\implies N_r = N_s',
        description: 'Under healthy steady-state excitation, rotor speed N_r matches synchronous speed N_s exactly.'
      },
      {
        label: 'Field Pole Magnetic Flux MMF',
        latex: '\\Phi_{\\text{pole}} = \\frac{N_f I_f}{\\mathcal{R}_{\\text{core}}}',
        description: 'Rotor field flux per pole is directly generated by DC field current I_f through N_f turns.'
      },
      {
        label: 'Exciter Contact Arc Heating',
        latex: 'P_{\\text{arc}} \\propto I_f^2 R_{\\text{contact}}',
        description: 'Electrical arcing across DC excitation slip rings scales with field current square and contact resistance.'
      }
    ],
    failureModes: [
      {
        title: 'Field Loss (Loss of Excitation) & Asynchronous Pull-Out',
        description: 'Open circuit or exciter failure drops field current I_f → 0. Excitation voltage collapses E_f → 0, developed power drops, and the motor snaps out of synchronism (s > 0), inducing destructive high-voltage spikes.',
        relatedEquations: ['Developed Synchronous Power', 'Zero Slip Synchronous Condition'],
        image3d: '/motors/wound-field-synchronous-motor/field-loss-hazard.png'
      },
      {
        title: 'Field Winding Inter-Turn Short & Shaft Bowing',
        description: 'Short-circuiting turns in a rotor pole coil reduces local flux Φ_1 < Φ_2. The resulting Unbalanced Magnetic Pull (UMP) creates 1x RPM radial vibration and asymmetric thermal shaft bowing.',
        relatedEquations: ['Field Pole Magnetic Flux MMF'],
        image3d: '/motors/wound-field-synchronous-motor/field-interturn-short.png'
      },
      {
        title: 'Exciter Slip-Ring Arcing & Brush Degradation',
        description: 'Continuous sliding contact conducts DC excitation current I_f. Friction and arcing cause surface pitting, voltage ripple, and localized thermal hotspots across rings.',
        relatedEquations: ['Exciter Contact Arc Heating'],
        image3d: '/motors/wound-field-synchronous-motor/exciter-slip-ring.png'
      }
    ],
    sensorPlan: [
      {
        sensor: 'Optical Tachometer / Position Encoder',
        purpose: 'Synchronous Out-of-Step Pull-Out Detection',
        howItWorks: 'Monitors exact speed N_r; if s > 0 occurs under load, detects out-of-step pull-out and executes an immediate AC mains trip command.',
        relatedEquation: 'Zero Slip Synchronous Condition'
      },
      {
        sensor: 'DC Current Shunt + Isolation Amp',
        purpose: 'DC Field Loss & Current Anomaly Monitoring',
        howItWorks: 'Measures I_f continuously; an abrupt drop in I_f combined with stator current surges signals loss of excitation.',
        relatedEquation: 'Developed Synchronous Power'
      },
      {
        sensor: 'A3144 Hall Effect Sensor (Non-Contact Rotor Flux)',
        purpose: 'Rotor Pole Magnetic Flux Asymmetry Sensing',
        howItWorks: 'Monitors external magnetic flux distribution every revolution to detect inter-turn shorts in rotor pole coils.',
        relatedEquation: 'Field Pole Magnetic Flux MMF'
      },
      {
        sensor: 'Acoustic-Optical Sensor Fusion (INMP441 + UV/IR)',
        purpose: 'Exciter Slip Ring Arcing Diagnostics',
        howItWorks: 'Fuses acoustic arcing noise (INMP441) with UV/IR photodiode spark counts to monitor DC exciter brush wear.',
        relatedEquation: 'Exciter Contact Arc Heating'
      },
      {
        sensor: 'MPU6050 Accelerometer',
        purpose: '1x RPM UMP & Thermal Shaft Bowing Diagnostics',
        howItWorks: 'Tracks 1x RPM radial vibration peaks caused by pole magnetic unbalance and thermal shaft distortion.',
        relatedEquation: 'Field Pole Magnetic Flux MMF'
      },
      {
        sensor: 'MLX90614 Non-Contact IR Sensor',
        purpose: 'Exciter Housing & Field Coil Thermal Logging',
        howItWorks: 'Tracks thermal rise rate dT/dt at DC slip rings and rotor pole end-turns to prevent insulation breakdown.',
        relatedEquation: 'Exciter Contact Arc Heating'
      }
    ],
    summary: [
      'High-power megawatt-class motor topology providing zero-slip constant speed and grid power factor correction.',
      'Critical risk: Loss of excitation (I_f → 0) triggers violent asynchronous pull-out and high-voltage coil induction.',
      'Sensor array monitors DC field current, non-contact rotor flux symmetry, exciter arcing, and 1x RPM UMP vibration.'
    ]
  },
  {
    category: 'AC',
    family: 'Synchronous',
    slug: 'pmsm-motor',
    name: 'Permanent Magnet Synchronous Motor (PMSM)',
    overview: 'State-of-the-art high-efficiency AC synchronous motor replacing rotor field coils with high-density rare-earth permanent magnets (NdFeB). Driven by 3-phase sinusoidal VFD inverters with zero rotor copper losses.',
    keyEquations: [
      {
        label: 'Electromagnetic d-q Axis Torque',
        latex: 'T_e = \\frac{3}{2} P \\left[ \\Psi_m I_q + (L_d - L_q) I_d I_q \\right]',
        description: 'Torque developed in d-q rotor coordinates based on magnet flux linkage \\Psi_m and reluctance torque difference (L_d - L_q).'
      },
      {
        label: 'Thermal Magnet Remanence Function',
        latex: 'B_r(T) = B_r(T_0) \\cdot \\left[ 1 + \\alpha \\cdot (T - T_0) \\right]',
        description: 'Models magnet remanence flux reduction as rotor temperature T approaches demagnetization knee point.'
      },
      {
        label: 'Spinning Magnet Short-Circuit Current',
        latex: 'I_{\\text{short}} = \\frac{\\omega_e \\Psi_{m,\\text{short}}}{Z_{\\text{short}}}',
        description: 'Spinning rotor magnets continuously induce high local short-circuit current in shorted stator turns even with inverter turned off.'
      }
    ],
    failureModes: [
      {
        title: 'Thermal & Demagnetization Cascade',
        description: 'Elevated rotor temperatures T > T_knee cause permanent remanence loss (B_r ↓). Dropping flux linkage Ψ_m forces the drive to draw higher current I_q to sustain load, accelerating thermal losses P = I²R in a destructive feedback loop.',
        relatedEquations: ['Electromagnetic d-q Axis Torque', 'Thermal Magnet Remanence Function'],
        image3d: '/motors/pmsm-motor/demagnetization-cascade.png'
      },
      {
        title: 'Stator Inter-Turn Short & High dV/dt VFD Stress',
        description: 'High dV/dt inverter switching wavefronts degrade stator slot varnish. Spinning rotor magnets continuously induce heavy short-circuit current I_short through transformer action, causing localized coil burnout.',
        relatedEquations: ['Spinning Magnet Short-Circuit Current'],
        image3d: '/motors/pmsm-motor/stator-pmsm-fault.png'
      },
      {
        title: 'Inverter Shaft Voltage & Bearing Fluting (EDM)',
        description: 'High switching frequency common-mode voltage discharges across bearing grease film via micro-arcs, causing microscopic pitting and bearing raceway fluting.',
        relatedEquations: ['Electromagnetic d-q Axis Torque'],
        image3d: '/motors/pmsm-motor/bearing-edm-fluting.png'
      }
    ],
    sensorPlan: [
      {
        sensor: 'Three-Phase Current Sensor Array (ACS712/ACS758)',
        purpose: 'd-q Current Demagnetization & Phase Symmetry Tracking',
        howItWorks: 'Monitors I_A, I_B, I_C and transforms to d-q frame to track quadrature current I_q spikes driven by magnet flux fade.',
        relatedEquation: 'Electromagnetic d-q Axis Torque'
      },
      {
        sensor: 'A3144 Hall Effect Sensor Array',
        purpose: 'Direct Rotor Magnet Flux Fade Monitoring',
        howItWorks: 'Measures rotor magnetic flux density B_actual over time to detect irreversible demagnetization before total drive failure.',
        relatedEquation: 'Thermal Magnet Remanence Function'
      },
      {
        sensor: 'Multi-Point Infrared Thermal Proxies (MLX90614)',
        purpose: 'Rotor Casing & Stator PWM Hotspot Tracking',
        howItWorks: 'Monitors rotor casing and stator coil surface temperatures to enforce safety limits below T_knee.',
        relatedEquation: 'Thermal Magnet Remanence Function'
      },
      {
        sensor: 'MPU6050 3-Axis Accelerometer',
        purpose: 'High-Frequency Bearing Fluting FFT Diagnostics',
        howItWorks: 'Performs spectral FFT analysis on high-frequency vibration to isolate bearing fluting pass frequencies.',
        relatedEquation: 'Spinning Magnet Short-Circuit Current'
      },
      {
        sensor: 'Fast Inverter Microsecond Hardware Comparator',
        purpose: 'Instant Gate Inverter Disconnection',
        howItWorks: 'Monitors phase current lines to trip gate drivers within <2µs during stator inter-turn shorts.',
        relatedEquation: 'Spinning Magnet Short-Circuit Current'
      }
    ],
    summary: [
      'Ultra-high efficiency brushless AC motor topology with zero rotor copper losses.',
      'Vulnerable to irreversible magnet demagnetization (T > T_knee) and spinning magnet short-circuit generator action.',
      '3-phase d-q current monitoring, direct Hall flux tracking, and microsecond inverter protection form the core defense.'
    ]
  }
];

export function getMotorBySlug(slug: string): MotorType | undefined {
  return motorsData.find((motor) => motor.slug === slug);
}

export function getUniqueCategories(): ('DC' | 'AC')[] {
  return Array.from(new Set(motorsData.map((m) => m.category)));
}

export function getUniqueFamilies(): string[] {
  return Array.from(new Set(motorsData.map((m) => m.family)));
}
